version: '3'
services:
  pod:
    image: allonvendia/scrapy.1.1.4
    container_name: "kk"
    restart: always
    volumes:
      - /home/www/comics:/home/comics
    environment:
      SOURCE_URL: "www.kuaikanmanhua.com"
    network_mode: "host"
    shm_size: '7gb'